spring:
  application:
    name: itinerary-assistant
  datasource:
    url: jdbc:postgresql://localhost:5432/tripplanner
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true